### ISSUE TITLE
Performance issues with Puma 3.x

### ISSUE THREAD

**Issue by DannyBen** [banister/binding_of_caller#59]
Hello,

We are experiencing significant slowness that seems to be caused by `binding_of_caller` when it is used in conjunction with Puma 3.x and the `better_errors` gem.

Puma 2.16.0 - no issues
Puma 3.0.0 and the latest 3.1.1 - slow to load.

The issue was originally opened as a [better_errors issue](https://github.com/charliesome/better_errors/issues/341#issuecomment-199981941), but it seems to be related to `binding_of_caller`.

Any additional details we can provide to assist in the debugging?

**Comment by cannikin** [comment]
I think this is actually due to something about Rails object structure. Some instance variable is now references a very deeply nested object structure that just takes a long time to dump. I've seen a 2MB+ payload come back from the server just when displaying the right column, before even trying to interact with with the REPL.

If you don't mind forgoing the dumped list of local, instance and rack session variables that display below the REPL then check this out: https://github.com/charliesome/better_errors/issues/341#issuecomment-264012862

**Comment by RobinDaugherty** [comment]
This seems to be purely a Better Errors performance issue, which hopefully was addressed by https://github.com/BetterErrors/better_errors/pull/402
